name: First workflow
on : push

jobs: 
 build:
    runs-on: ubuntu-latest
    steps:
      -name: checkout code
       uses: actions/checkout@v4

      -name: Print Hello message
        run: echo "Hello from Github actions!"
